import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ActiveLink } from "@/components/atoms/ActiveLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav className="p-4">
					<ul className="flex items-center justify-center gap-2">
						<li>
							<ActiveLink href="/">Home</ActiveLink>
						</li>
						<li>
							<ActiveLink href="/products">Products</ActiveLink>
						</li>
						<li>
							<ActiveLink href="/privacy-policy">Privacy policy</ActiveLink>
						</li>
					</ul>
				</nav>
				<main className="mx-auto max-w-7xl p-4">{children}</main>
			</body>
		</html>
	);
}
